Engines/apps/user_room/config/routes.rb
module UserRoom
  # include ::UserRoom::Routes.mixin(self)
  class Routes
    def self.mixin mapper
      mapper.extend ::UserRoom::DefaultRoutes
      mapper.send :user_room_routes
    end
  end

  module DefaultRoutes
    def user_room_routes
      devise_for :users, path: '',
        :path_names => {
          sign_in:  'login',
          sign_up:  'signup',
          sign_out: 'logout'
        },
        :controllers => {
          :omniauth_callbacks => "devise_controllers/omniauth_callbacks",
          :confirmations      => "devise_controllers/confirmations",
          :registrations      => "devise_controllers/registrations",
          :sessions           => "devise_controllers/sessions",
          :passwords          => "devise_controllers/passwords"
        }

      devise_scope :user do
        get  'account_should_be_activate' => 'devise_controllers/registrations#account_should_be_activate'

        post 'create_email_registration_request'        => 'devise_controllers/registrations#create_email_registration_request',   as: :create_email_registration_request
        get  'activate_email_registration_request/:uid' => 'devise_controllers/registrations#activate_email_registration_request', as: :activate_email_registration_request

        post 'create_onetime_login_link'        => 'devise_controllers/sessions#create_onetime_login_link',   as: :create_onetime_login_link
        get  'activate_onetime_login_link/:uid' => 'devise_controllers/sessions#activate_onetime_login_link', as: :activate_onetime_login_link

        delete 'omniauth/provider/:provider' => 'devise_controllers/omniauth_callbacks#delete_provider', as: :delete_provider
      end

      # Personal
      get  "profile"       => "users#profile",       as: :profile
      post "autologin/:id" => 'users#autologin',     as: :autologin

      resources :users, only: %w[ index show edit update ] do
        patch  :change_password

        member do
          patch  :avatar_crop_1x1

          patch  :avatar_rotate_left
          patch  :avatar_rotate_right

          delete :avatar_delete
        end
      end
    end
  end
end

Engines/apps/user_room/app/models/concerns/user_room/social_networks/login.rb
module UserRoom
  module SocialNetworks
    module Login

      extend ActiveSupport::Concern

      # `User` model have to have the following fields
      #
      # gp_addr
      # fb_addr
      # vk_addr
      # tw_addr
      # ok_addr
      #
      # has_many :credentials

      class_methods do
        def networks_list
          %w[ vkontakte facebook twitter google_oauth2 odnoklassniki ]
        end

        def social_networks_hash
          {
            gp: :Google,
            fb: :Facebook,
            vk: :Vkontakte,
            tw: :Twitter,
            ok: :Odnoklassniki
          }
        end

        def social_networks_hash2
          {
            gp: :google_oauth2,
            fb: :facebook,
            vk: :vkontakte,
            tw: :twitter,
            ok: :odnoklassniki
          }
        end
      end # class_methods

      def actual_email
        return '' if email.match(/#{ oauth_default_email_domain }/mix)
        email
      end

      included do
        attr_accessor :oauth_data

        has_many :credentials, dependent: :destroy
        before_validation :oauth_actions, on: :create, if: ->{ oauth? }

        validate :uniq_credential, if: ->{ oauth? }

        # =================================================
        # CREDANTIALS
        # =================================================

        def oauth_create_credential!
          uid          = oauth_params['uid']
          provider     = oauth_params['provider']
          _credentials = oauth_params.try(:[], 'credentials')

          exp_date = nil
          exp_date = (Time.now + _credentials['expires_at'].to_i.seconds) if _credentials['expires_at'].present?

          credentials_record = credentials.where(provider: provider).first

          if credentials_record.blank?
            credentials_record = credentials.create(
              uid:        uid,
              provider:   provider,
              expires_at: exp_date,
              access_token: _credentials['token'],
              access_token_secret: _credentials['secret'] # twitter
            )
          end

          credentials_record
        end

        def add_credential(omniauth)
          uid          = omniauth['uid']
          provider     = omniauth['provider']
          _credentials = omniauth.try(:[], 'credentials')

          exp_date = nil
          exp_date = (Time.now + _credentials['expires_at'].to_i.seconds) if _credentials['expires_at'].present?

          credentials_record = credentials.where(provider: provider).first

          if credentials_record.blank?
            credentials_record = credentials.create(
              uid:        uid,
              provider:   provider,
              expires_at: exp_date,
              access_token: _credentials['token'],
              access_token_secret: _credentials['secret'] # twitter
            )
          end

          credentials_record
        end

        def reset_oauth_data!
          self.oauth_data, @oauth_params = [ nil, nil ]
        end

        private

        def oauth_actions
          oauth_set_email
          oauth_set_password

          oauth_set_login
          oauth_set_username
          oauth_set_avatar_url

          oauth_set_common_params
          oauth_set_social_network_url
        end

        def oauth_default_email_domain
          'theopencms.org'
        end

        # USER SIDE VARIABLES
        def oauth_set_username
          self.username = info.try(:[], 'name')
        end

        def oauth_set_login
          self.login = raw_info.try(:[], 'screen_name') if vk_oauth?
          self.login = info.try(:[], 'nickname')        if tw_oauth?
        end

        def oauth_set_email
          self.email   = "#{ SecureRandom.hex[0..6] }@#{ oauth_default_email_domain }"
          self.email ||= info.try(:[], 'email')
        end

        def oauth_set_password
          self.password = SecureRandom.hex[0..10]
        end

        # =================================================
        # OAUTH SET/UPDATE VARIABLES
        # =================================================

        def oauth_set_avatar_url
          # self.avatar_url = oauth_get_avatar_url
          self.avatar = ::URI.parse oauth_get_avatar_url
        end

        def oauth_set_common_params
          # set something common here
        end

        def oauth_set_social_network_url omniauth = nil
          _info = omniauth ? omniauth.try(:[], 'info') : info

          if _info.present?
            ::User.social_networks_hash.each_pair do |key, name|
              network_field = "#{ key }_addr" # fb_addr

              # if self.respond_to?('fb_addr') && self.fb_addr.blank?
              if self.respond_to?(network_field) && self.send(network_field).blank?
                # social_network_url = info['urls']['Google']
                # self.fb_addr = social_network_url
                social_network_url = _info.try(:[], 'urls').try(:[], name.to_s)
                self.try "#{ network_field }=", social_network_url
              end
            end # each_pair
          end # if _info.present?
        end

        # =================================================
        # OAUTH helpers
        # =================================================

        def oauth?; oauth_data.present?; end

        ::User.social_networks_hash2.each_pair do |k, name|
          # EXAMPLE: def og_oauth?; oauth_params['provider'] == 'facebook'; end
          define_method "#{ k }_oauth?" do
            oauth_params['provider'] == name.to_s
          end
        end

        def oauth_params
          @oauth_params ||= (begin; JSON.parse oauth_data; rescue; oauth_data; end)
        end

        def info
          @info ||= oauth_params.try(:[], 'info')
        end

        def extra
          @extra ||= oauth_params.try(:[], 'extra')
        end

        def raw_info
          @raw_info ||= oauth_params.try(:[], 'extra').try(:[], 'raw_info')
        end

        # =================================================
        # AVATAR
        # =================================================

        def oauth_get_avatar_url
          avatar = info.try(:[], 'image')
          gp_avatar, fb_avatar, tw_avatar = Array.new(3, avatar)

          if fb_oauth?
            json   = ::JSON.parse(Net::HTTP.get(URI.parse(fb_avatar.gsub('&redirect=false', '') + '?type=large&redirect=false')))
            avatar = json['data']['url'] unless json['data']['is_silhouette']
          end

          if tw_oauth?
            avatar = tw_avatar.gsub('_normal', '')
          end

          if vk_oauth?
            avatar = raw_info.try(:[], 'photo_200_orig')
          end

          if gp_oauth?
            avatar = gp_avatar.gsub('s50', 's200').gsub('sz=50', 'sz=200')
          end

          if ok_oauth?
            avatar = raw_info.try(:[], 'pic_2')
          end

          avatar
        end

        # =================================================
        # VALIDATION
        # =================================================
        def uniq_credential
          uid      = oauth_params['uid']
          provider = oauth_params['provider']

          if ::Credential.find_by_uid_and_provider(uid, provider)
            errors.add :credentials, :uniqueness
          end
        end
      end # included

    end # Login
  end # SocialNetworks
end # UserRoom

# ru:
#   activerecord:
#     attributes:
#       user:
#         credentials: "Аккаунт социальной сети"
#     errors:
#       models:
#         user:
#           attributes:
#             credentials:
#               uniqueness: "уже привязан к другому пользователю"

Engines/apps/user_room/app/models/concerns/user_room/user_content_processing.rb
module UserRoom
  module UserContentProcessing
    def content_processing!(user = self)
      self.login = login.to_s.to_slug_param
      self.about = process_content(raw_about, user)
    end

    private

    def process_content(text, user)
      text.to_s.squish.strip
    end
  end
end

Engines/apps/user_room/app/controllers/concerns/user_room/controller_avatar_actions.rb
# include ::UserRoom::ControllerAvatarActions
module UserRoom
  module ControllerAvatarActions

    AVATAR_ACTIONS_NAMES = %w[
      avatar_crop_1x1
      avatar_rotate_left
      avatar_rotate_right
      avatar_delete
    ]

    def avatar_crop_1x1
      crop_params = params[:crop].permit(:img_w, :x, :y, :w, :h).to_h.symbolize_keys
      path = @user.avatar_crop_1x1(crop_params)
      render json: { ids: { '.js-user_avatar-v1x1' => path } }
    end

    def avatar_rotate_left
      @user.avatar_rotate_left
      redirect_back fallback_location: root_path
    end

    def avatar_rotate_right
      @user.avatar_rotate_right
      redirect_back fallback_location: root_path
    end

    def avatar_delete
      @user.avatar_destroy!
      redirect_back fallback_location: root_path
    end
  end
end

Engines/apps/user_room/app/controllers/concerns/user_room/controller_callbacks.rb
# include ::UserRoom::ControllerCallbacks
module UserRoom
  module ControllerCallbacks
    extend ActiveSupport::Concern

    included do
      before_action :authenticate_user!,  if: :needs_authenticate_user?
      before_action :set_role!,           if: :needs_set_role?
      before_action :authorize_action!,   if: :needs_authorize_action?

      before_action :set_resource_class!, if: :needs_set_resource_class?
      before_action :set_resource!,       if: :needs_set_resource?

      before_action :authorize_owner!,    if: :needs_authorize_owner?
    end

    protected

    ################################################
    # Authorization
    ################################################

    def authorize_action!
      return if can_perform?(controller_name, action: action_name)
      authorization_exception!('Action is not allowed to perform')
    end

    def set_resource!
      user_id = params[:id] || params[:user_id]
      @resource = @user = ::User.where(login: user_id).first
    end

    def authorize_owner!
      owner = current_user.owner?(@resource)
      authorization_exception!('Owner required') unless owner
    end

    ################################################
    # Do We Need to Perform a Callback?
    ################################################

    def needs_authenticate_user?
       except_actions = %w[index show]
      !except_actions.include?(action_name)
    end

    def needs_set_role?
       except_actions = %w[index]
      !except_actions.include?(action_name)
    end

    def needs_authorize_action?
       except_actions = %w[index show]
      !except_actions.include?(action_name)
    end

    def needs_set_resource_class?
       except_actions = %w[]
      !except_actions.include?(action_name)
    end

    def needs_set_resource?
       except_actions = %w[index]
      !except_actions.include?(action_name)
    end

    def needs_authorize_owner?
       except_actions = %w[index show profile]
      !except_actions.include?(action_name)
    end

    def needs_authorize_admin?
       except_actions = %w[index show] + user_avatar_actions
      !except_actions.include?(action_name)
    end

    def user_avatar_actions
      ::UserRoom::ControllerAvatarActions::AVATAR_ACTIONS_NAMES
    end
  end # ControllerRestrictions
end

Engines/apps/user_room/app/controllers/concerns/user_room/store_devise_redirect_location.rb
# include UserRoom::StoreDeviseRedirectLocation
module UserRoom
  module StoreDeviseRedirectLocation
    extend ActiveSupport::Concern

    included do
      after_filter :store_devise_redirect_location
    end # included

    # store last url - this is needed for post-login redirect to whatever the user last visited.
    def store_devise_redirect_location
      return if  request.xhr?
      return if !request.get?

      not_store_for = {
        registrations: %w[ new ],
        confirmation:  %w[ new ],
        sessions:      %w[ new ],
        passwords:     %w[ new edit ],
        omniauth_callbacks: %[ vkontakte facebook twitter google_oauth2 odnoklassniki failure ],

        users:   %w[ profile ],
        carts:   %w[ index ],
        orders:  %w[ index ]
      }.with_indifferent_access

      return if not_store_for.try(:[], controller_name).try(:include?, action_name)

      cookies[:previous_location] = request.fullpath
    end

  end # RedirectLocation
end # UserRoom

Engines/apps/user_room/app/controllers/concerns/user_room/user_avatar_actions.rb
# include ::UserRoom::UserAvatarActions
module UserRoom
  module UserAvatarActions

    AVATAR_ACTIONS_NAMES = %w[
      avatar_crop_1x1
      avatar_rotate_left
      avatar_rotate_right
      avatar_delete
    ]

    def avatar_crop_1x1
      crop_params = params[:crop].permit(:img_w, :x, :y, :w, :h).to_h.symbolize_keys
      path = @user.avatar_crop_1x1(crop_params)
      render json: { ids: { '.js-user_avatar-v1x1' => path } }
    end

    def avatar_rotate_left
      @user.avatar_rotate_left
      redirect_back fallback_location: root_path
    end

    def avatar_rotate_right
      @user.avatar_rotate_right
      redirect_back fallback_location: root_path
    end

    def avatar_delete
      @user.avatar_destroy!
      redirect_back fallback_location: root_path
    end
  end
end

Engines/apps/user_room/app/controllers/concerns/user_room/users_controller.rb
# include ::UserRoom::UsersController
module UserRoom
  module UsersController
    extend ActiveSupport::Concern

    included do
      layout -> { layout_template }
      include ::UserRoom::ControllerAvatarActions
      include ::UserRoom::ControllerCallbacks
    end

    ##########################################
    ### Public actions
    ##########################################

    def index
      @users = ::User
        .max2min(:created_at)
        .simple_sort(params)
        .pagination(params)

      @users_count = ::User.count
    end

    def show; end

    ##########################################
    ### Restricted actions
    ##########################################

    def edit; end

    def update
      @user.assign_attributes(permitted_params)
      @user.content_processing!(current_user)

      if @user.save
        sign_in(@user, bypass: true) if permitted_params[:password].present?
        redirect_to edit_user_path(@user), notice: _t(:changes_saved)
      else
        @user.reload
        render 'users/edit'
      end
    end

    def profile
      @user = current_user
    end

    def change_password
      @user.send_reset_password_instructions
      redirect_to url_for([:edit, @user]), notice: _t(:password_instructions_sent)
    end

    ##########################################
    ### Admin Actions
    ##########################################

    def autologin
      user = ::User.where(login: params[:id]).first
      sign_in(user, bypass: true)
      redirect_to profile_path
    end

    private

    def layout_template
      public_actions = %w[show index]
      return 'user_room_frontend' if public_actions.include?(action_name)
      'user_room_backend'
    end

    def _t(name)
      t("user_room.controllers.users.#{name}")
    end

  end # UsersController
end

Engines/apps/user_room/app/helpers/user_room_helper.rb
module UserRoomHelper
  def default_user_avatar(user, opts = {})
    klass  = opts[:class]
    width  = opts[:width]  || 100
    height = opts[:height] || 100
    id = Digest::SHA256.hexdigest(user.login)

    content_tag :canvas, nil, class: klass, width: width, height: height, 'data-jdenticon-hash' => id
  end

  def user_room_date_format(date)
    I18n.l(date, format: "%-d %B %Y")
  end
end

Engines/apps/user_room/app/views/user_room/users/_admin_profile.slim
content_for :title do
  | Admin UI

.m20
  .fs20.mb40

  .ptz_table.ptz_table-0.w100p
    .ptz_thead.fs18
      .ptz_tr
        .ptz_th.p25 My Profile
        .ptz_th.p25 Profile Edit
    .ptz_tbody
      .ptz_tr
        .ptz_td.p25
          .mb20 = link_to 'My Profile', @user, class: 'ptz_btn ptz_size-14'
          .mb20 = link_to "Profile Edit", [ :edit, @user ], class: 'ptz_btn ptz_size-14'

Engines/apps/user_room/app/views/user_room/users/_user_profile.slim
= render template: 'users/edit'

Engines/apps/user_room/app/views/user_room/users/edit.slim
ruby:
  voiceless { Article }

- content_for :title do
  | Edit the Profile

.m15
  = render partial: 'notifications/form', locals: { object: @user, format: :html }

  .fs28.lh120.mb20
    = t(:title, scope: 'user_room.users.edit')

  - if defined?(Article) && can_perform?(:publication, action: [:manage, :my])
    .user_room_form-block.mb20
      .m20
        - if can_perform?(:publication, action: :manage)
          = link_to 'Edit Articles', manage_articles_path, class: 'ptz_btn ptz_size-16'

        - if can_perform?(:publication, action: :my)
          = link_to 'Edit My Articles', my_articles_path, class: 'ptz_btn ptz_size-16'

  .user_room_form-block.mb20
    .m20
      = render partial: 'user_room/avatar/uploader', locals: { object: @user }

  .user_room_form-block.mb20
    .m20
      = render template: 'user_room/users/edit/basic_info'

  .user_room_form-block.mb20
    .m20
      .mb20.fs16.b = t(:title, scope: 'user_room.users.edit.social_networks')
      = render template: 'user_room/users/edit/social_networks_credentials'

  .user_room_form-block.mb20
    .m20
      = render template: 'user_room/users/edit/social_networks'

  .user_room_form-block.mb20
    .m20
      = render template: 'user_room/users/edit/update_password'

Engines/apps/user_room/app/views/user_room/users/index.slim
- if (paginator = paginate @users, views_prefix: 'protozaur/paginator').present?
  .mt20.mb20= paginator

.tar.fs16.mb30.pr10
  span.b> Items amount:
  - %w[ 5 10 20 50 100 125 ].each do |num|
    ruby:
      is_current = 'b' if params[:per_page] == num

    span.mr10 = link_to num, url_for(per_page: num), class: is_current

  span.mr10= link_to '[x]', reset_simple_sort(per_page: nil)

table.ptz_table.w100p.h100p.user_room_list-block
  tbody
    tr.tal.fs18.br-off
      th.p20
      th.p20 = link_to 'Login ↕',     simple_sort_url(:login),      title: :login
      th.p20 = link_to 'Name ↕',      simple_sort_url(:username),   title: :username
      th.p20 About
      th.p20.tar = link_to 'Create at ↕', simple_sort_url(:created_at), title: :created_at

    - @users.each do |user|
      tr.user_room_list-row.fs16.lh120
        td.p20
          = link_to user do
            - if user.avatar.present?
              = image_tag user.avatar.url(:v100x100), class: 'user_room_list-avatar_image'
            - else
              = default_user_avatar(user, {class: 'user_room_list-avatar_image'})

        td.p20.vam = user.login
        td.p20.vam.br-off = user.username
        td.p20.vam.w100p = user.about
        td.p20.vam.tar.br-off = user_room_date_format(user.created_at)

Engines/apps/user_room/app/views/user_room/users/profile.slim
- if current_user.admin?
  = render partial: 'users/admin_profile'
- else
  = render partial: 'users/user_profile'

Engines/apps/user_room/app/views/user_room/users/show.slim
- content_for :title do
  = t 'users_page', scope: :user_room

.ptz_table
  .ptz_tr
    .ptz_td.p20
      .mb20
        - if @user.avatar.present?
          = image_tag @user.avatar.url(:v100x100), class: 'user_room_list-avatar_image'
        - else
          = default_user_avatar(@user, {class: 'user_room_list-avatar_image'})

      - if current_user && current_user == @user
        = link_to 'Edit', [:edit, @user], class: 'ptz_btn ptz_btn-size-s'
    .ptz_td.p20
      .mt20
        - if current_user.try(:admin?)
          - if current_user != @user
            .mb20
              = link_to 'Login as', autologin_path(@user), method: :post, class: 'ptz_btn ptz_size-12'

        - if @user.username.present?
          .fs15.mb15
            span.b Name:
            '
            = @user.username

        - if @user.login.present?
          .fs15.mb15
            span.b Login:
            '
            = @user.login

        .fs15.mb15
          span.b<> Created at:
          = user_room_date_format(@user.created_at)

        ruby:
          soc_nets = {
            gp: :Google,
            fb: :Facebook,
            vk: :Vkontakte,
            tw: :Twitter,
            ok: :Odnoklassniki
          }

        ul.ul.mt20.mb20
          - soc_nets.each_pair do |abbr, title|
            ruby:
              soc_addr = "#{abbr}_addr"
              field_addr = @user.send(soc_addr)

            - if field_addr.present?
              li.fs15.mb5
                = link_to title, field_addr, target: :_blank

        - if @user.about.present?
          .fs16.b.mb20 About

          .fs16.mt20.mb20
            = @user.about