Engines/apps/user_room/config/routes.rb
module UserRoom
  # include ::UserRoom::Routes.mixin(self)
  class Routes
    def self.mixin mapper
      mapper.extend ::UserRoom::DefaultRoutes
      mapper.send :user_room_routes
    end
  end

  module DefaultRoutes
    def user_room_routes
      devise_for :users, path: '',
        :path_names => {
          sign_in:  'login',
          sign_up:  'signup',
          sign_out: 'logout'
        },
        :controllers => {
          :omniauth_callbacks => "devise_controllers/omniauth_callbacks",
          :confirmations      => "devise_controllers/confirmations",
          :registrations      => "devise_controllers/registrations",
          :sessions           => "devise_controllers/sessions",
          :passwords          => "devise_controllers/passwords"
        }

      devise_scope :user do
        get  'account_should_be_activate' => 'devise_controllers/registrations#account_should_be_activate'

        post 'create_email_registration_request'        => 'devise_controllers/registrations#create_email_registration_request',   as: :create_email_registration_request
        get  'activate_email_registration_request/:uid' => 'devise_controllers/registrations#activate_email_registration_request', as: :activate_email_registration_request

        post 'create_onetime_login_link'        => 'devise_controllers/sessions#create_onetime_login_link',   as: :create_onetime_login_link
        get  'activate_onetime_login_link/:uid' => 'devise_controllers/sessions#activate_onetime_login_link', as: :activate_onetime_login_link

        delete 'omniauth/provider/:provider' => 'devise_controllers/omniauth_callbacks#delete_provider', as: :delete_provider
      end

      # Personal
      get  "profile"       => "users#profile",       as: :profile
      post "autologin/:id" => 'users#autologin',     as: :autologin

      resources :users, only: %w[ index show edit update ] do
        patch  :change_password

        member do
          patch  :avatar_crop_1x1

          patch  :avatar_rotate_left
          patch  :avatar_rotate_right

          delete :avatar_delete
        end
      end
    end
  end
end

Engines/apps/user_room/app/models/concerns/user_room/user.rb
module UserRoom
  module User
    extend ActiveSupport::Concern

    included do
      devise :database_authenticatable,
        :confirmable,
        :recoverable,
        :validatable,
        :registerable,
        :rememberable,
        :omniauthable,
        :omniauth_providers => %w[
          facebook
          twitter
          vkontakte
          google_oauth2
          odnoklassniki
        ]

      include ::SimpleSort::Base
      include ::Pagination::Base
      include ::Notifications::LocalizedErrors

      include ::UserRoom::UserAvatar
      include ::UserRoom::UserContentProcessing

      include ::UserRoom::SocialNetworks::Login
      include ::UserRoom::SocialNetworks::Validations

      ##########################################
      ### Validations
      ##########################################

      validates :login, presence: true, uniqueness: true, on: :update, if: :login_changed?
      validate  :login_validations, on: :update, if: :login_changed?
      validates :password, length: { minimum: 6 }, if: ->{ password.present? }

      ##########################################
      ### Callbacks
      ##########################################

      after_create :set_default_login

      ##########################################
      ### Other methods
      ##########################################

      def to_param
        self.login
      end

      private

      def set_default_login
        self.update_column(:login, "id#{self.id}")
      end

      def login_validations
        unless (self.login =~ /[a-zA-Z]/mix)
          errors.add(:login, "has to have a one of more letters")
        end

        if self.login =~ /\Aid/mix
          if self.login.downcase != "id#{self.id}"
            errors.add(:login, "This Login could not be used")
          end
        end
      end

    end # included do
  end # User
end # UserRoom

Engines/apps/user_room/app/controllers/concerns/user_room/users_controller.rb
# include ::UserRoom::UsersController
module UserRoom
  module UsersController
    extend ActiveSupport::Concern

    included do
      layout -> { layout_template }
      include ::UserRoom::ControllerAvatarActions
      include ::UserRoom::ControllerCallbacks
    end

    ##########################################
    ### Public actions
    ##########################################

    def index
      @users = ::User
        .max2min(:created_at)
        .simple_sort(params)
        .pagination(params)

      @users_count = ::User.count
    end

    def show; end

    ##########################################
    ### Restricted actions
    ##########################################

    def edit; end

    def update
      @user.assign_attributes(permitted_params)
      @user.content_processing!(current_user)

      if @user.save
        sign_in(@user, bypass: true) if permitted_params[:password].present?
        redirect_to edit_user_path(@user), notice: _t(:changes_saved)
      else
        @user.reload
        render 'users/edit'
      end
    end

    def profile
      @user = current_user
    end

    def change_password
      @user.send_reset_password_instructions
      redirect_to url_for([:edit, @user]), notice: _t(:password_instructions_sent)
    end

    ##########################################
    ### Admin Actions
    ##########################################

    def autologin
      user = ::User.where(login: params[:id]).first
      sign_in(user, bypass: true)
      redirect_to profile_path
    end

    private

    def layout_template
      public_actions = %w[show index]
      return 'user_room_frontend' if public_actions.include?(action_name)
      'user_room_backend'
    end

    def _t(name)
      t("user_room.controllers.users.#{name}")
    end

  end # UsersController
end

Engines/apps/user_room/app/views/user_room/users/edit/basic_info.slim
= form_for @user, html: { class: '' } do |f|
  ruby:
    bi_title = t(:title, scope: 'user_room.users.edit.basic_info')
    bi_name  = t(:name, scope: 'user_room.users.edit.basic_info')
    bi_login = t(:login, scope: 'user_room.users.edit.basic_info')
    bi_email = t(:email, scope: 'user_room.users.edit.basic_info')
    bi_about = t(:about, scope: 'user_room.users.edit.basic_info')
    bi_btn   = t(:btn, scope: 'user_room.users.edit.basic_info')

  .mb20.fs16.b = bi_title

  .ptz_table.w100p
    .ptz_tr
      .ptz_td.w50p
        .mb15
          = f.label :username, bi_name, class: 'block fs14 lh120 mb5'
          = f.text_field :username, class: 'ptz_input w90p'

        .mb15
          = f.label :login, bi_login, class: 'block fs14 lh120 mb5'
          = f.text_field :login, class: 'ptz_input w90p'

        .mb15
          = f.label :email, bi_email, class: 'block fs14 lh120 mb5 '
          = f.text_field :email, class: 'ptz_input w90p'

        - if @user.unconfirmed_email
          .mb15
            .block.fs14.lh120.mb10 Unconfirmed Email:
            .b.mt15.fs15= @user.unconfirmed_email

      .ptz_td
        .mb15
          = f.label :raw_about, bi_about, class: 'block fs14 lh120 mb5'
          = f.text_area :raw_about, class: 'ptz_textarea w90p', rows: 5

  .mt10
    = f.submit bi_btn, class: 'ptz_btn ptz_size-14'

Engines/apps/user_room/app/views/user_room/users/edit/social_networks.slim
= form_for @user, html: { class: '' } do |f|
  ruby:
    snc_title = t(:title, scope: 'user_room.users.edit.social_network_contacts')
    snc_fb = t(:fb, scope: 'user_room.users.edit.social_network_contacts')
    snc_gp = t(:gp, scope: 'user_room.users.edit.social_network_contacts')
    snc_tw = t(:tw, scope: 'user_room.users.edit.social_network_contacts')
    snc_vk = t(:vk, scope: 'user_room.users.edit.social_network_contacts')
    snc_ok = t(:ok, scope: 'user_room.users.edit.social_network_contacts')
    snc_pt = t(:pt, scope: 'user_room.users.edit.social_network_contacts')
    snc_ig = t(:ig, scope: 'user_room.users.edit.social_network_contacts')
    snc_btn = t(:btn, scope: 'user_room.users.edit.social_network_contacts')

  .mb20.fs16.b = snc_title

  .ptz_table.w100p
    .ptz_tr
      .ptz_td.w50p
        .mb15
          = f.label :fb_addr, snc_fb, class: 'block fs14 lh120 mb5 '
          = f.text_field :fb_addr, class: 'ptz_input w90p'

        .mb15
          = f.label :tw_addr, snc_tw, class: 'block fs14 lh120 mb5 '
          = f.text_field :tw_addr, class: 'ptz_input w90p'

        .mb15
          = f.label :gp_addr, snc_gp, class: 'block fs14 lh120 mb5 '
          = f.text_field :gp_addr, class: 'ptz_input w90p'

        .mb15
          = f.label :ig_addr, snc_ig, class: 'block fs14 lh120 mb5 '
          = f.text_field :ig_addr, class: 'ptz_input w90p'

      .ptz_td
        .mb15
          = f.label :pt_addr, snc_pt, class: 'block fs14 lh120 mb5 '
          = f.text_field :pt_addr, class: 'ptz_input w90p'

        .mb15
          = f.label :vk_addr, snc_vk, class: 'block fs14 lh120 mb5'
          = f.text_field :vk_addr, class: 'ptz_input w90p'

        .mb15
          = f.label :ok_addr, snc_ok, class: 'block fs14 lh120 mb5'
          = f.text_field :ok_addr, class: 'ptz_input w90p'

  .mt20
    = f.submit snc_btn, class: 'ptz_btn ptz_size-14'

Engines/apps/user_room/app/views/user_room/users/edit/social_networks_credentials.slim
ruby:
  credentials = @user.credentials
  available_to_unlink = @user.credentials.count > 1

.ptz_table.w100p.mt30.mb30
  .ptz_tr
    ruby:
      nets = [
        [:facebook, :facebook, :fb, 500],
        [:twitter, :twitter, :tw, 700],
        [:google_oauth2, 'google-plus', :gp, 500],
        [:vkontakte, :vk, :vk, 500],
        [:odnoklassniki, :odnoklassniki, :ok, 650]
      ]

    - nets.each do |item|
        ruby:
          net_name   = item[0]
          fa_class   = item[1]
          short_name = item[2]
          height     = item[3]

        .ptz_td.w100.pr20.tac
          - if has_provider?(credentials, net_name)
            .social_login_btn-unlink_holder.p10
              = link_to '', jsvoid,
                class: "social_login_btn social_login_btn-linked social_login_btn-#{ short_name } fa fa-#{ fa_class }",
                title: t(short_name, scope: 'user_room.users.edit.social_networks')

              - if available_to_unlink
                = link_to delete_provider_path(net_name), method: :delete, class: 'social_login_btn-unlink' do
                  .fa.fa-times.social_login_btn-unlink_icon.fs15
          - else
            = link_to '', send("user_#{net_name}_omniauth_authorize_path"),
              data: { height: height },
              class: "js-social_login-btn social_login_btn social_login_btn-#{ short_name } fa fa-#{ fa_class }",
              title: t(short_name, scope: 'user_room.users.edit.social_networks')

          .fs12.ffa.mt10
            = t(short_name, scope: 'user_room.users.edit.social_networks')

Engines/apps/user_room/app/views/user_room/users/edit/update_password.slim
= form_for @user, html: { class: '' } do |f|
  ruby:
    cp_title = t(:title, scope: 'user_room.users.edit.change_password')
    cp_pass1 = t(:password, scope: 'user_room.users.edit.change_password')
    cp_pass2 = t(:confirm_password, scope: 'user_room.users.edit.change_password')
    cp_btn   = t(:btn, scope: 'user_room.users.edit.change_password')

  .mb20.fs16.b = cp_title

  .clearfix.mb15
    .pull-left.mr25
      = f.label :password, cp_pass1, class: 'block fs14 lh120 mb5 '
      = f.password_field :password, class: 'ptz_input w200'

    .pull-left
      = f.label :password_confirmation, cp_pass2, class: 'block fs14 lh120 mb5 '
      = f.password_field :password_confirmation, class: 'ptz_input w200'

  .mt20
    = f.submit cp_btn, class: 'ptz_btn ptz_size-14'